name: first
on: push #trigger
jobs:
    job1:
      name: First job
      runs-on: ubuntu-latest #bash
      steps:
      - name: Step one
        # execute an action
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort

    job2:
      name: Second job
      needs: job1 # make job2 dependable of job1 - it will only run after job1
      runs-on: windows-latest #Powershell
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env:  | Sort-Object Name"
